### ISSUE TITLE
Flow Stream

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#1]
1. Flow Stream chưa có save đc data
2. Flow Stream-STD value có thể lưu lại Grs vol data nhưng mà khi bỏ thêm data như BS&W thì Grs vol data biến mất và ko có lưu lại data mới
3. Flow Stream,  khi chọn 1 ngày mới (date) thì trang web ko tự refresh mà phải ấn load data

**Comment by hunglmtb** [comment]
mình trích từ file excel mà Hương gửi
1. Flow Stream chưa có save đc data
=>mình chưa rõ là rơi vào case nào, date, Facility, hay phase nào. mình check và thấy nó vẫn save đc. Hương có thể mô tả cụ thể hơn ko?  
2. Flow Stream-STD value có thể lưu lại Grs vol data nhưng mà khi bỏ thêm data như BS&W thì Grs vol data biến mất và ko có lưu lại data mới
=> fix sau  
3. Flow Stream,  khi chọn 1 ngày mới (date) thì trang web ko tự refresh mà phải ấn load data
=> mình đang làm theo hệ thống cũ là chỉ reload khi nhấn load data, mình sẽ fix sau  
4. Nút load data ko có đổi qua refresh sau khi load data lần đầu tiên
=>fixed.  
5. Ko thể dùng nút enter trên bàn phím để log in  
=>fixed.  
6. Energy Builder, khi khéo từ trái qua phải thì càng kéo thì tên của mấy cột biến mất và kéo hoài
=> chưa hiểu lắm, Hương mô tả cụ thể hơn ko

**Comment by huongdle** [comment]
1. Flow Stream đã save đc data nhưng mà lúc nó báo data saved thì cái ô vàng bên trên quá dài. =>Anh đổi lại để chỉ có chữ 'data saved' đc ko ạ?
2. Flow Stream-STD value có thể lưu lại Grs vol data nhưng mà khi bỏ thêm data như BS&W thì Grs vol data biến mất và ko có lưu lại data mới
   => fix sau
3. Flow Stream, khi chọn 1 ngày mới (date) thì trang web ko tự refresh mà phải ấn load data
   =>cái này ko cần gấp, anh sửa cái này sau cũng ok
4. Energy Unit, khi khéo từ trái qua phải thì càng kéo thì tên của mấy cột biến mất và kéo hoài
   => Lúc mà anh vào phần Energy Unit rồi FDC, sau đó nếu kéo cái bar từ trái qua phải, thì càng kéo nó càng dài, ko có điểm dừng. Và càng kéo thì nó xuất hiện khoảng trống ở bên phía trên tên của mấy cột. Khoảng trống xuất hiện giữa Press UOM và Object Name (Object Name bị move).

5.Tại sao em ko thấy tên của mấy tên object trong Energy Unit?

**Comment by hunglmtb** [comment]
> 1. Flow Stream đã save đc data nhưng mà lúc nó báo data saved thì cái ô vàng bên trên quá dài. =>Anh đổi lại để chỉ có chữ 'data saved' đc ko ạ?

mình sẽ note cái này để fix sau nhé

> 1. Energy Unit, khi khéo từ trái qua phải thì càng kéo thì tên của mấy cột biến mất và kéo hoài
>    => Lúc mà anh vào phần Energy Unit rồi FDC, sau đó nếu kéo cái bar từ trái qua phải, thì càng kéo nó càng dài, ko có điểm dừng. Và càng kéo thì nó xuất hiện khoảng trống ở bên phía trên tên của mấy cột. Khoảng trống xuất hiện giữa Press UOM và Object Name (Object Name bị move).

Hương test trên trình duyệt nào để a check lại?

> 5.Tại sao em ko thấy tên của mấy tên object trong Energy Unit?

Hương thử chọn    Energy Unit Group là No group, điều kiện filter để có kết quả, a sẽ update No group thành default selected
