### ISSUE TITLE
Contract data detail

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#105]
A, phần contract data này thiếu nguyên 1 phần contract detail ở bên dưới. Cái này là a thiếu hay là mình ko cần nữa? e xem trên .co server thì mỗi cái contract sẽ có contract detail ở bên dưới. có gì e skype call a

**Comment by hunglmtb** [comment]
cái này chuyển lên popup sau khi select nhé. hội ý vs a Tùng rồi vì làm như thế cho thống nhất

**Comment by huongdle** [comment]
Good
