### ISSUE TITLE
Well test hrs và min

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#11]
Khi chọn giờ hoặc phút trong Well test (FDC, STD) thì mình nên để 1 cái label ở bên trên để biết cái nào là giờ cái nào là phút

=> cái này để em skype call anh, em chỉ anh xem thì dễ hơn

**Comment by hunglmtb** [comment]
a thấy style này thì hiển thị luôn được thông tin hour và minutes này
am or pm
hiện tại a thêm option này vào
