### ISSUE TITLE
Back to home

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#110]
Cái này là thêm, e muốn là mỗi lần người dùng ấn vào chữ EB, thì cái trang mà có hình tổ ong hiện ra, trang đầu tiên khi login ý ạ.

Rồi khi ấn vào chữ production, thì trang tổ ong của phần production sẽ hiện ra

và mấy trang khác cũng thế. 

A làm cho e nhé

**Comment by hunglmtb** [comment]
done

**Comment by huongdle** [comment]
Good
