### ISSUE TITLE
Change password screen

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#116]
Cái phần change password screen

Bỏ Personal setting lên trên Date time format

Bỏ Number configuring xuống dưới date time format

Đổi 'Submit' của date/time and number thành 'Apply'

cái này chắc a e mình skype call nhau sau, để a rõ hơn chứ e nói chắc a cũng ko hiểu :)

**Comment by huongdle** [comment]
A bỏ thêm cho e chữ "Change Date/Time Format' ngay trên chỗ thay đổi và cho em "Change Decimal Mark" lên trên phần đó luôn.

A cho chữ nhỏ lại 1 tí cũng đc, ko cần phải to đâu, để cho nó có đủ chỗ

**Comment by hunglmtb** [comment]
cái này call skype cho dễ hiểu :))

**Comment by hunglmtb** [comment]
fixed

**Comment by huongdle** [comment]
Good
