### ISSUE TITLE
Tổ ong

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#117]
chẳng biết giải thích sao cho a hiểu

e ấn vào chữ production thì nó đưa em trở về cái tổ ong của phần production management nhé, xong em ấn cái backspace để quay ra tổ ong chính. Rồi em vào phần Data Visuliazation rồi ấn vào network model, thì sau khi ấn, system đưa em quay trở lại tổ ong chứ ko phải là mở cái network  model.

Đó, a thử tái hiện lại xem có đc ko, xong nói em biết

**Comment by hunglmtb** [comment]
ok. a tái hiện được và fixed rồi :)

**Comment by huongdle** [comment]
good
