### ISSUE TITLE
Cargo entry/cargo nomination

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#121]
Trong cái cargo entry có mấy cái đã đc nominate (dấu check) nhưng mà lúc e sang bên cargo nomination, thì ko thấy những dữ liệu đã đc nominate hiện lên bên cargo nomination. 

A xem lại phần này cho e

**Comment by hunglmtb** [comment]
bên nomination sẽ filter theo storage, còn bên entry thì tất cả storage thuộc facility
e check lại xem có đúng như vậy ko

**Comment by huongdle** [comment]
Good

**Comment by hunglmtb** [comment]
check lại cargo ABC ko hiển thị bên nomination vì Request Date là 30/6 trong khi entry là 1/7
do lúc trước chưa fix time bị lệch nên bị
sau này fix bug này nên ko thấy nữa. e check lại xem

**Comment by huongdle** [comment]
Good
