### ISSUE TITLE
Cargo Load

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#122]
![untitled193](https://cloud.githubusercontent.com/assets/19290058/18686631/30a354f6-7f42-11e6-9dac-9ed7618293fc.png)

Cái end time của phần này ko hiện lên sau khi e đã chọn ngày

**Comment by hunglmtb** [comment]
cần nêu các steps để reproduce

**Comment by huongdle** [comment]
Tự fix rồi ạ
