### ISSUE TITLE
EU Theoretical

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#13]
Theoretical của EU sẽ tính sau khi thiết lập công thức trong equation editor. 
Trong EU, theoretical, ngày 1 tháng 4, 2016, có 1 số xuất hiện trong data, số này cần delete

**Comment by edataviz** [comment]
@Hương: Các con số này là được tính toán từ FDC đưa qua mỗi khi bấm Save, vì bên FDC có số liệu nên nó được tính qua bên Theor. Sao lại cần delete?
