### ISSUE TITLE
SCSSV, edv3

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#134]
cái SCSSV này làm xong chưa ạ?

**Comment by hunglmtb** [comment]
@thevinhdev e xem issue này nhé

**Comment by thevinhdev** [comment]
SCSSV e làm xong rùi chị nhé.. mysql & sql-server

**Comment by huongdle** [comment]
vậy nó báo lỗi này là sao?
![image](https://user-images.githubusercontent.com/19290058/29377115-60f4e510-8280-11e7-9bc8-edbf0e1ccbe7.png)

**Comment by thevinhdev** [comment]
chị test trên ie11 ạ? e chưa test trên browser này. :((

**Comment by edataviz** [comment]
Lỗi này do thiếu bảng trong database, anh đã sửa rồi nhé.
Tùng
