### ISSUE TITLE
Temp UOM

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#16]
Temp UOM trong FS, FDC value chỉ hiện ra Celsius, mà cần hiện ra thêm Fahrenheit, trong database có Fahrenheit nhưng trên FDC screen thì ko có. Anh xem lại tại sao lại ko hiện lên

**Comment by hunglmtb** [comment]
Temp UOM này lấy theo facility theo UOM_TYPE, cái facility có uom_type = 1;
Celsius  có uom_type =1 nên đc lấy ra
Fahrenheit  thì có uom_type =2 nên ko đc lấy ra

**Comment by huongdle** [comment]
Thì giờ anh set lại để nó hiện ra đầy đủ đi ạ, tại vì ngày trước cái này làm cho hãng kia nên anh Tùng anh set như vậy. Giờ mình làm chung chung thì anh cho hiện lên hết như trong database

**Comment by huongdle** [comment]
#19 #18 #17

**Comment by huongdle** [comment]
UOM trong EU #19 
Press UOM #17 
Vol UOM #18

**Comment by hunglmtb** [comment]
vì data liên quan đến nhiều bảng nên để a bảo a TÙng gửi bản data đầy đủ, ko nó có thể phát sinh bugs khác liên quan

**Comment by hunglmtb** [comment]
a confirm  vs anh Tùng rồi, cái này chỉ cần setting trong database là được.
HIện tại a mới setting cho Press UOM #17 
Vol UOM #18
e thấy cái nào cần setting lại thì vào server vs port 433 để setting lại nhé
