### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#2]
1. Storage, cái ô vàng báo data đã save quá dài, nếu data save đc thì chỉ cần để 'data saved'
2. Em thử bỏ data vào trong Tank Value rồi save lại, tại sao data của Tank Value lại xuất hiện ở trong Storage Value? 2 cái này sẽ có data khác nhau

**Comment by hunglmtb** [comment]
1.Storage, cái ô vàng báo data đã save quá dài, nếu data save đc thì chỉ cần để 'data saved'
=> để tiện cho fix bug nên a để nó notify về giá trị, cái này a sửa sau
2.Em thử bỏ data vào trong Tank Value rồi save lại, tại sao data của Tank Value lại xuất hiện ở trong Storage Value? 2 cái này sẽ có data khác nhau
=> storage value được tính toán từ giá trị của Tank Value, nên khi Tank Value thay đổi thì giá trị bên Storage Value cũng đc thay đổi
a update nhiều sửa đổi trong chức năng storage, Hương thử check lại nhé
