### ISSUE TITLE
Chỉnh cho đều 

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#21]
Anh có thể chỉnh lại để làm sao mà mọi thứ nhìn nó đều chút. Như là cái box CSV ý, thì anh chỉnh lại để nó nằm ngay dưới chữ CSV, hiện tại nó nằm lệch sang bên trái.

Với lại object name với mấy cái ngay bên cạnh (inj, active, gas) thì cho nó nằm bằng nhau, hiện tại hơi lệch. 
Anh xem lại rồi chỉnh lại cho em nhé.

**Comment by hunglmtb** [comment]
a update theo yêu cầu rồi nhé.
e check lại
sorry vì a dùng chrome , mấy cái này bị trên firefox :D
