### ISSUE TITLE
EU saving data

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#22]
Khi em bỏ data vào trong STD value tab, thì mỗi một lần em chì save đc 1 data thôi. Anh chỉnh lại để có thể save đc nhiều data cùng 1 lúc

**Comment by hunglmtb** [comment]
a ko reproduce được, a input nhiều fields, trên nhiều rows khác nhau, vẫn save được

**Comment by huongdle** [comment]
nhiều row thì ok, nhưng nhiều hàng dọc thì ko đc ạ

**Comment by hunglmtb** [comment]
fixed
