### ISSUE TITLE
Gas vol trong Energy Unit

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#30]
Khi bỏ grs vol cho gas trong FDC value tab, EM 33, thì lúc save system ko có save đúng. Em có thể cho anh xem qua skype, em nghĩ nó bị hỏng cái gì đó trong lúc anh bỏ code mới lên

**Comment by hunglmtb** [comment]
e check lại formula của item đó nhé

**Comment by huongdle** [comment]
The grs vol in STD being calculate to standard temp and press, therefore the grs vol is different. If just input the data straight into STD, then the input will be the same.
