### ISSUE TITLE
Tank vol

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#32]
Lúc em bỏ data vào begin vol và end vol bên FDC tank, system vẫn save nhưng ko có display đúng data, save xong thì 2 phần này thành số khác. Nhưng nếu input data lại và save lần 2 thì system save đúng. Để em show anh trên skype cho anh thấy

**Comment by hunglmtb** [comment]
e check lại formula của item đó nhé

**Comment by huongdle** [comment]
When input data into FDC, the data is exactly as the report, but when the data goes to STD, all the data in FDC such as grs vol, end/begin vol, will be calculate under standard temp and pressure
