### ISSUE TITLE
Workflow run task

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#35]
Khi em làm config the task trong workflow, em chọn screen xong save, thì system vẫn save. Có điều khi mở lại cái config the task cho 1 hình, thì cái screen em chọn cho run task lại trở thành default task, chứ ko phải task em đã chọn và save. 
Cái này lúc trước anh sửa rồi, giờ nó bị lại

**Comment by edataviz** [comment]
Fixed
