### ISSUE TITLE
Workflow notification 

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#36]
Khi em ấn nút run cho cái workflow thì em ko thấy đèn báo hiệu sáng ở trên chỗ bánh xe, anh xem lại cho em

**Comment by edataviz** [comment]
Hương, mỗi khi run 1 workflow thì nó sẽ thực hiện các task theo trình tự. Việc thực hiên này có thể là tự động hoặc manual. Có thể cái task được thực hiện tới không được gán cho user đang đăng nhập thì nó sẽ không được tính (không được báo hiệu). Em cần check lại xem em đã chạy workflow nào, check xem cái task có được gán cho user của em không.

**Comment by huongdle** [comment]
em chạy workflow manhnv, cái mà report test run là assign user tên em. Em chạy mà ko thấy nó nổi notification lên trên phía cái gear của màn hình của em

**Comment by edataviz** [comment]
Mạnh xử lý lại điều kiện "where" của user. Hiện tại nếu thêm dấu phảy vào sau user (huong,) thì nó mới chạy đúng.

**Comment by edataviz** [comment]
Fixed
