### ISSUE TITLE
Safety

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#37]
Trong safety, cái occurence anh set nó thành là date, cái này chỉ là input số thôi, em chỉnh trong port 443 rồi. Nhưng lúc save thì nó vẫn save là date format. Anh xem ngày mùng 1 tháng 4

**Comment by hunglmtb** [comment]
fixed rồi nhé, do setting sang column create_date, anh set lại column count rồi

**Comment by huongdle** [comment]
fixed
