### ISSUE TITLE
Mạnh - Workflow - Lỗi khi lưu

### ISSUE THREAD

**Issue by edataviz** [hunglmtb/eb#40]
Hiện tượng: bấm run workflow, số đếm task trên góc màn hình tăng lên (vì có task của user đang chạy). Sau đó bấm Save workflow thì số đếm task này bị trở lại ban đầu, mặc dù trạng thái của workflow vẫn là đang chạy.

Nguyên nhân: Có thể do khi lưu lại workflow, trạng thái của các task bị reset lại là chưa chạy.

Xử lý: cần giữ nguyên trạng thái của các task mỗi khi save lại workflow.
![image](https://cloud.githubusercontent.com/assets/15412943/16039536/a494b282-3254-11e6-882f-9e8272792380.png)
Bỏ cái option Config Run này đi. Mỗi khi lưu lại thì giữ nguyên trạng thái hiện tại của workflow. Nếu là tạo mới (hoặc save as new) thì để trạng thái là "chưa chạy".

**Comment by manhnv3434** [comment]
em fix cai nay rui anh nhe, anh check cho e.

**Comment by huongdle** [comment]
Fixed
