### ISSUE TITLE
report part 3

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#41]
em mở report mà page nó bị error, anh xem lại

**Comment by manhnv3434** [comment]
Cái này là do tomcat trên server bi stop nên bị vậy, anh start lại rùi, anh check lại thấy Ok, e check lại nhé.

**Comment by huongdle** [comment]
Sao lúc anh check thì ok, em check thì lại ko ok chút nào. em check cả chrome và firefox, đều ko mở đc

**Comment by huongdle** [comment]
fixed for now
