### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#42]
Workflow ko có hiện lên cái "your task" khi em ấn vào bánh xe. Em có run cái workflow đó.

Hiện tại em thấy trên cái bánh xe, nó cứ hiện lên cái báo hiệu nút đỏ, cái đó chỉ hiện lên khi nào mà run cái task thôi chứ ạ

**Comment by edataviz** [comment]
Fixed, em check lại nhé

**Comment by huongdle** [comment]
em chạy đc cái task đầu tiên ok, tại em chạy cái task report, thì tất cả ok. Em có thể finish task report đó. Xong em open task flow stream, thì open đc,  nhưng vì A. Mạnh chưa connect nên là cái page nó để là error. Xong em ấn back, mở cái task ra thì ko thấy workflow hiện lên nữa, vì lúc này em muốn fisnish cái task flow stream. anh xem lại cho em, nếu ko em làm cho anh xem cũng đc

**Comment by huongdle** [comment]
![untitled164](https://cloud.githubusercontent.com/assets/19290058/16083110/737218ea-32d9-11e6-98a6-7ce868bc23e1.png)

**Comment by huongdle** [comment]
Fixed
