### ISSUE TITLE
Equipment

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#43]
mấy cái cột hours ko có save đúng input data, em bỏ số nhỏ mà lúc save nó đổi thành số lớn ko à

**Comment by hunglmtb** [comment]
e check lại formula nhé

**Comment by huongdle** [comment]
hôm nay em test, em phát hiện ra 1 điều. khi em bỏ data mới vào 1 cái equipment, thì yesterday hours reading lúc nào cũng là số 2291, em thử cả ngày mùng 1 tháng và ngày 31 tháng 3

**Comment by huongdle** [comment]
hôm nay em test, em phát hiện ra 1 điều. khi em bỏ data mới vào 1 cái equipment, thì yesterday hours reading lúc nào cũng là số 2291, em thử cả ngày mùng 1 tháng và ngày 31 tháng 3

**Comment by huongdle** [comment]
Fixed
