### ISSUE TITLE
Storage data connected

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#5]
.Em thử bỏ data vào trong Tank Value rồi save lại, tại sao data của Tank Value lại xuất hiện ở trong Storage Value? 2 cái này sẽ có data khác nhau
=> storage value được tính toán từ giá trị của Tank Value, nên khi Tank Value thay đổi thì giá trị bên Storage Value cũng đc thay đổi
a update nhiều sửa đổi trong chức năng storage, Hương thử check lại nhé

=> Tank value với storage value ko liên quan tới nhau, data của 2 cái này ko thể connect với nhau như hiện tại. Data của tank value sẽ khác với data của storage value.
hiện tại thì CTP D101 Oil Tank ( Tank value) connect với CTP Produced Oil Storage (Storage value) 
CTP G/P Drain connect với CTP Produced Water Storage (Storage value)

**Comment by hunglmtb** [comment]
thực tế thì giá trị bên  storage value là tổng của các tank bên  Tank value.
cái này là implement theo chức năng cũ yêu cầu.
Huong có thể check trên đây
http://energybuilder.co/eb/dc/storage.php
note là: server này và server Hương đang test của a có database khác nhau,a sẽ dựng thêm cái system cũ trên database Hương đang test sớm nhất để nhất quán hơn
