### ISSUE TITLE
Ticket report date and ticket type

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#58]
Sau khi em select cái report date với ticket type trong phần ticket, thì em ấn save, nhưng mà sau khi save xong, thì 2 phần này ko hiển thị trên màn hình, anh xem lại cho em.

Em đang test data ngày mùng 1 tháng 7

**Comment by hunglmtb** [comment]
fixed.
do db mới có thêm 2 fields này

**Comment by huongdle** [comment]
good
