### ISSUE TITLE
Thiếu ticket trong dropdown list

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#61]
Khi em đưa chuột vào 'function' - ' Production management' thì em ko thấy ticket hiện ra trên list, anh xem lại cho em 

![untitled177](https://cloud.githubusercontent.com/assets/19290058/16954873/2d5251c0-4d98-11e6-94d0-63443d49d019.png)

**Comment by hunglmtb** [comment]
cái này chuẩn bị thay đổi và sửa lại menu, nên sẽ update trong cái menu mới này :)

**Comment by huongdle** [comment]
Good
