### ISSUE TITLE
Deferment duration

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#63]
Cái duration bị tính sai, em chọn từ 8h sáng đến 5h chiều cùng 1 ngày, mà system tính sao mà thành -9, em đang test ngày mùng 1 tháng 7. anh xem lại giúp em

**Comment by hunglmtb** [comment]
fixed. do config formula cho duration của Deferment trong field config bị ngược

**Comment by huongdle** [comment]
Good
