### ISSUE TITLE
Formular edit button

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#69]
cái edit button ok rồi ạ, nhưng mà sau em khi click vô đó và ấn 'Save' hay 'Save as new' thì 2 cái này ko hoạt động. Anh xem lại
![untitled179](https://cloud.githubusercontent.com/assets/19290058/17027683/7691c530-4f2a-11e6-90ec-74d6ce995610.png)

**Comment by huongdle** [comment]
cái nút save với save as new, em biết nó bị bug chỗ nào rồi. mỗi 1 cái công thức chỉ đc save hoặc save as 1 lần, sau 1 lần ấn save đó thì lần thứ 2 save ko đc. cái này anh phải fix lại, để lúc nào thay đổi công thức đều save hoặc save as đc

**Comment by hunglmtb** [comment]
fixed. cái này do date bị lỗi khi save
a cũng thêm cài format date theo config khi hiển thị luôn tại đây

**Comment by huongdle** [comment]
sau mỗi lần e save, thì em chỉ save đc 1 lần thôi. Để e chỉ cho anh nhé
1. CP flow formula
2. chọn CTP Gas Produced, ấn Edit 
3. Chọn object name là CTP total processes gas rồi ấn save
4. Chọn ESS produced oil test, ấn Edit
5. Chọn object name là ESS oil produced, rồi ấn save

A sẽ thấy lần thứ 2 save sẽ ko save đc. A thử tái hiện lại nhé

**Comment by huongdle** [comment]
Good
