### ISSUE TITLE
EU ko có lưu lại data

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#7]
Sau khi bỏ data vào active hours, grs vol, choke,v.v, ấn nút save và thấy giống như là data đã save. nhưng khi ấn refresh thì ko thấy data hiện ra nữa 
Cái này đều xảy ra trong FDC value và STD value

**Comment by hunglmtb** [comment]
fixed
1 số fields được tính toán, nên nếu thiếu data để tính toán cho công thức nó sẽ quẳng thông báo lỗi về

**Comment by huongdle** [comment]
EU-FDC value, để save grs vol trong FDC thì phải có API, Temp, và Press. Nhưng mà grs vol data vẫn ko save kể cả khi có API, Temp, và Press
Error message 'Can not calculate conversion for ENERGY_UNIT ID 216 (Check API, Temperature, Pressure value)'
