### ISSUE TITLE
New formula button

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#70]
cái add new formula này cũng bị giống như edit formua, cái nút 'Save' với 'Save new formula' ko có chạy

**Comment by hunglmtb** [comment]
fixed nhé. refer #69

**Comment by huongdle** [comment]
e có save đc đâu

**Comment by huongdle** [comment]
add new variable, thì object name ko có refresh khi chọn object type

**Comment by hunglmtb** [comment]
fixed

**Comment by huongdle** [comment]
Good
