### ISSUE TITLE
Object name, table data

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#72]
Khi em ấn vào 'edit' của phần variable, thì cái bảng edit hiện ra, nhưng sau khi em thoát ra thì tên của object name với tên của column bị biến mất. anh xem lại
![untitled180](https://cloud.githubusercontent.com/assets/19290058/17029296/59467c9a-4f30-11e6-864a-a8b572787074.png)

**Comment by hunglmtb** [comment]
skype

**Comment by huongdle** [comment]
Good
