### ISSUE TITLE
Config Alloc

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#79]
cái config allocation nó có chút vấn đề, nhưng chắc chắn em phải cho anh xem em làm thì anh mới hiểu. 

mỗi lần em save cái runner sau khi edit, thì mấy cái tên của object nó bị duplicate

em nói sơ qua vậy thôi, có gì em sẽ làm cho anh xem

**Comment by huongdle** [comment]
cái config allocation ko có show diagram như trong server cũ

**Comment by manhnv3434** [comment]
Cái duplicate anh xử lý xong rùi nhé

**Comment by huongdle** [comment]
Good
