### ISSUE TITLE
Cargo entry date

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#82]
cái date ko đc chuẩn, nhảy ngày loạn lên, anh xem lại nhé

**Comment by huongdle** [comment]
chú tam mới nói anh Tùng bỏ thêm to date và from date vào phần cargo entry, khi nào anh tùng làm xong thì anh bỏ lên cái server mới cho em nhé

**Comment by hunglmtb** [comment]
cái thêm todate và from date a hiểu. done nhé
nhảy loạn lên a ko tái hiện được
đợi e share screen

**Comment by huongdle** [comment]
good
