### ISSUE TITLE
Cargo nomination

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#83]
cái date của cargo nomination cũng bị như cargo entry, nó ko save đúng ngày đã đc chọn

**Comment by huongdle** [comment]
anh chỉnh lại chỗ tên của mấy tên columns, nó hiện tại đang có chữ background gì gì đó

**Comment by hunglmtb** [comment]
a fixed mấy columns rồi nhé, DB đưa config vào title column @@

**Comment by huongdle** [comment]
Good
