### ISSUE TITLE
Cargo nomination save

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#84]
hình như a bỏ code mới lên nó ảnh hưởng tới cargo nomination, e save ko đc dữ liệu mới

**Comment by hunglmtb** [comment]
có ràng buộc trong nomination là nếu cargo có id đã đc nominated thì sẽ không add loại này nữa, có thể  cargo này thuộc storage khác nên ko được display .
e check lại xem

**Comment by huongdle** [comment]
e đồng ý là nếu đã nominated bên cargo entry thì ko cần nominate bên cargo nomination. nhưng mà e làm thử 1 cái bên cargo entry chưa có nominate, mà e vẫn ko save đc ở bên nomination

**Comment by huongdle** [comment]
e làm thử record mới cho cargo nomination mới, save thì hình như là ok rồi, nhưng save xong thì dữ liệu ko có hiện lên trên màn hình. Nếu a check bên cargo entry thì sẽ thấy tất cả đều đã nominate nhưng bên nomination thì ko hiện ra record nào cả. E check trong cả db nhưng cũng ko thấy hiện lên, a xem lại nhé

**Comment by huongdle** [comment]
Good
