### ISSUE TITLE
chữ mầu đen

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#89]
e phát hiện ra chữ save với chữ subnetworks của network model và workflow bị mầu đen, trong khi đó mấy chữ khác mầu trắng hết

**Comment by hunglmtb** [comment]
fixed

**Comment by huongdle** [comment]
Network model: sub network vẫn còn mầu đen
Workflow: Save và swimlane vẫn còn mầu đen

**Comment by huongdle** [comment]
Good
