### ISSUE TITLE
Tên

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#90]
Tên của demurrage, cargo document, và cargo status, tên của mấy phần này ko có hiện ra trên phần menu bar giống bên production

![untitled188](https://cloud.githubusercontent.com/assets/19290058/17306640/b5d507e6-57f6-11e6-9322-c479743c2080.png)
![untitled187](https://cloud.githubusercontent.com/assets/19290058/17306642/ba98a6e8-57f6-11e6-9ff7-d3bd20837510.png)

**Comment by hunglmtb** [comment]
fixed

**Comment by huongdle** [comment]
Good
