### ISSUE TITLE
Energy Unit ko có save

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#96]
E đang test lại, thì em thử save data trong FDC Value, e bỏ cả API, Temp, và Pres, nhưng system ko có save. A xem lại cho e với

**Comment by hunglmtb** [comment]
cái này do trong fields config không có hiển thị 3 columns của api, temp, pres nên nó hiển thị thông báo thiếu 3 fields kia. e check lại xem tại sao lại ẩn 3 columns này để đưa ra cách giải quyết

**Comment by huongdle** [comment]
e thấy ko phải chỉ có 3 cái columns đấy bị ẩn đâu. cái nào cũng bị ẩn, nếu a xem thì sẽ thấy cái columns nào cũng ko thể thay đổi đc tên, e ko biết lý do tại sao

**Comment by hunglmtb** [comment]
cần call skype cho rõ :)

**Comment by hunglmtb** [comment]
tính toán Bg phức tạp còn tùy theo là gas hay oil và table qltydata có data hay liên quan đến cả thành phần khí như 'C1' 
'C2' 
'C3' 
'C4I'
'C4N'
'C5I'
'C5N'
'C6' 
'C7' 
'H2S'
'CO2'
'N2' 
trong trường hợp gas.
nên khi thiếu các dữ liệu này nó sẽ ko tính toán đc và quẳng ra cái thông báo kia.
Hiện tại check thì thấy phần qltydata cho 1 số energy unit đều ko có nên không thể tính toán được.
có những trường hợp tính toán được đối với phase type là oil: "West Marine 24" phase là Oil
để tính toán được cho gas thì cần bổ sung qltydata cho phần này

**Comment by hunglmtb** [comment]
bên cái flow
input bên std data ok.
sau đó input bên flc thì bên std mất
a check lại do tính toán từ fdc đổ sang std, giá trị tính toán trung gian bg = null nên trả về giá trị null khi update db. system cũ cũng làm như thế trong case này
như thế nếu thay đổi thì phải thống nhất lại trong trường hợp này update null hay keep giá trị input bên fdc

**Comment by huongdle** [comment]
cái này a cứ để như vậy đi, e sẽ nói chú tam test, nếu chú thấy gì ko đúng thì mình sửa sau. Tại vì mình làm theo system cũ mà

**Comment by huongdle** [comment]
Good
