### ISSUE TITLE
Energy Unit well status

### ISSUE THREAD

**Issue by huongdle** [hunglmtb/eb#97]
Trong STD Value có 1 phần là Well Status, thì theo như server cũ, cái này hiện tại là text input, nhưng đúng của nó phải là drop down list. Và drop down list của nó có auto, online, offline. 

A xem lại có phải thế ko, nếu ko thì có gì mình skype rồi e cho a xem

**Comment by hunglmtb** [comment]
fixed

**Comment by huongdle** [comment]
Good
